### ISSUE TITLE
The "detail" link in pull request is point to "unconfigured-jenkins-location/job..."

### ISSUE THREAD

**Issue by butterandfly** [jenkinsci/github-organization-folder-plugin#19]
After create a new pull request, we can check the build status of the pr. But the "detail" button's href is "unconfigured-jenkins-location/...". 
By the way I am using a slave to do the building jobs.

**Comment by rtyler** [comment]
This is due to whatever is configured as the "Jenkins URL" in the instances System Configuration (Manage Jenkins > Configure Jenkins). There you should set the appropriate URL of your Jenkins instance.

E.g. for my instance on a host named `blackberry` I can go to to `http://blackberry:8080/configure` and set:

![jenkins-url](https://cloud.githubusercontent.com/assets/26594/17406714/7522d744-5a19-11e6-9bbf-553bd9abc6e5.png)
